name: chack_project
description: 'Chack - 채크'
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  # SVG 이미지 렌더링을 위한 패키지
  flutter_svg: ^2.0.9
  image_picker: ^1.1.2

  # Firebase 관련 패키지
  firebase_core: ^2.32.0
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.2.0
  google_sign_in: ^6.1.6

  # Permission 핸들러
  permission_handler: ^10.2.0

  # API 키 등 중요 정보를 .env 파일로 관리하기 위한 패키지
  flutter_dotenv: ^5.2.1

  # 애플리케이션의 상태를 관리하기 위한 패키지
  provider: ^6.1.1

  # HTTP 통신을 위한 패키지
  http: ^0.13.4

  # 지도 API를 사용하기 위한 패키지
  synchronized: ^3.1.0
  geolocator: ^8.0.0
  geocoding: ^2.1.0

  # device info 패키지
  device_info_plus: ^9.1.1

  # 캐시 등 공유 정보를 저장하기 위한 패키지
  shared_preferences: ^2.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  percent_indicator:
    ^4.2.2 # pub.dev에서 최신 버전 확인
    #to support korean language
  flutter_localizations:
    sdk: flutter
  logger: ^1.4.0

  # 통계 화면에서 필요한 패키지
  fl_chart: ^0.65.0
  table_calendar: ^3.0.10

  # 알림을 위한 패키지
  flutter_local_notifications: ^15.1.3

  # url_launcher 패키지
  url_launcher: ^6.2.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - .env

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SUITE
      fonts:
        - asset: assets/fonts/SUITE-Light.ttf
          weight: 300
        - asset: assets/fonts/SUITE-Regular.ttf
          weight: 400
        - asset: assets/fonts/SUITE-Medium.ttf
          weight: 500
        - asset: assets/fonts/SUITE-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SUITE-Bold.ttf
          weight: 700
        - asset: assets/fonts/SUITE-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/SUITE-Heavy.ttf
          weight: 900
